DROPS = [
    {
        "id": "1",
        "name": "Royal Pop",
        "brand": "Swatch",
        "location": "ION Orchard, Level 1",
        "dropTime": "10:00 AM, 18 May",
        "queueOpen": "8:00 AM",
        "estimatedWait": "2h 40min",
        "currentSlot": 7,
        "totalSlots": 200,
        "status": "hot",
        "imagePlaceholderColor": "#1a0a2e",
        "latitude": 1.3040,
        "longitude": 103.8318,
        "sourceUrl": None,
        "sourceLabel": None,
    },
    {
        "id": "2",
        "name": "SB Dunk Low",
        "brand": "Nike",
        "location": "Nike Orchard Road",
        "dropTime": "11:00 AM, 18 May",
        "queueOpen": "9:00 AM",
        "estimatedWait": "1h 55min",
        "currentSlot": 23,
        "totalSlots": 150,
        "status": "filling",
        "imagePlaceholderColor": "#0a1a2e",
        "latitude": 1.3036,
        "longitude": 103.8322,
        "sourceUrl": None,
        "sourceLabel": None,
    },
    {
        "id": "3",
        "name": "Labubu Series 3",
        "brand": "Pop Mart",
        "location": "Bugis Junction",
        "dropTime": "12:00 PM, 18 May",
        "queueOpen": "10:00 AM",
        "estimatedWait": "3h 10min",
        "currentSlot": 2,
        "totalSlots": 100,
        "status": "hot",
        "imagePlaceholderColor": "#1a1a0a",
        "latitude": 1.2990,
        "longitude": 103.8554,
        "sourceUrl": None,
        "sourceLabel": None,
    },
]

TRANSPORT_BY_LOCATION = {
    "ION Orchard, Level 1": {
        "travelMinutes": 28,
        "line": "Circle Line -> Orchard",
        "walkingDistanceMeters": 420,
        "firstDeparture": "Now",
        "leaveAt": "07:17 AM",
        "interchange": "No interchange",
        "nearestStop": "Orchard Station",
    },
    "Nike Orchard Road": {
        "travelMinutes": 24,
        "line": "North-South Line -> Orchard",
        "walkingDistanceMeters": 360,
        "firstDeparture": "Now",
        "leaveAt": "08:21 AM",
        "interchange": "No interchange",
        "nearestStop": "Orchard Station",
    },
    "Bugis Junction": {
        "travelMinutes": 31,
        "line": "Downtown Line -> Bugis",
        "walkingDistanceMeters": 280,
        "firstDeparture": "Now",
        "leaveAt": "09:14 AM",
        "interchange": "No interchange",
        "nearestStop": "Bugis Station",
    },
}

WEATHER_BY_LOCATION = {
    "ION Orchard, Level 1": "Light rain - umbrella advised",
    "Nike Orchard Road": "Cloudy and humid - hydrate before arrival",
    "Bugis Junction": "Passing showers - sheltered route recommended",
}
